# Generated by Django 4.0.6 on 2022-07-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Life_Expectance',
            new_name='Life_Expectancy',
        ),
    ]
