# Generated by Django 4.0.6 on 2022-07-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigdata', '0002_rename_life_expectance_life_expectancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='life_expectancy',
            options={'verbose_name_plural': 'Life Expectancy'},
        ),
        migrations.AddField(
            model_name='life_expectancy',
            name='age',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
